config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :goals do
    put :mark_complete
    resources :goal_updates
  end

  get 'welcome/index'
  get 'welcome/index/:expand', to: 'welcome#index'
  get 'goals/index/:metagoal_id', to: 'goals#index'
  
  root 'welcome#index'

end

app/models/goal_update.rb
class GoalUpdate < ActiveRecord::Base
	extend SimpleCalendar
  		has_calendar :attribute => :created_at
	belongs_to :goal
end

app/controllers/goal_updates_controller.rb
class GoalUpdatesController < ApplicationController
  before_action :set_goal_update, only: [:show, :edit, :update, :destroy]

  before_action :set_goal

  before_action :authenticate_user!

  
  # GET /goal_updates
  # GET /goal_updates.json
  def index
    @goal_updates = GoalUpdate.where(goal_id: @goal.id)
    @current_goal = params[:goal_id]
  end

  # GET /goal_updates/1
  # GET /goal_updates/1.json
  def show
  end

  # GET /goal_updates/new
  def new
    @goal_update = GoalUpdate.new
  end

  # GET /goal_updates/1/edit
  def edit
  end

  # POST /goal_updates
  # POST /goal_updates.json
  def create
    @goal_update = GoalUpdate.new(goal_update_params)

    respond_to do |format|
      if @goal_update.save
        format.html { redirect_to [@goal, @goal_update], notice: 'Goal update was successfully created.' }
        format.json { render :show, status: :created, location: @goal_update }
      else
        format.html { render :new }
        format.json { render json: @goal_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goal_updates/1
  # PATCH/PUT /goal_updates/1.json
  def update
    respond_to do |format|
      if @goal_update.update(goal_update_params)
        format.html { redirect_to [@goal, @goal_update], notice: 'Goal update was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal_update }
      else
        format.html { render :edit }
        format.json { render json: @goal_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goal_updates/1
  # DELETE /goal_updates/1.json
  def destroy
    @goal_update.destroy
    respond_to do |format|
      format.html { redirect_to goal_goal_updates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal_update
      @goal_update = GoalUpdate.find(params[:id])
    end

    def set_goal
      @goal = Goal.find(params[:goal_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_update_params
      params.require(:goal_update).permit(:goal_id, :entry, :update_date)
    end
end

app/helpers/goal_updates_helper.rb
module GoalUpdatesHelper

end

app/views/goal_updates/_form.html.erb
<%= form_for([@goal, @goal_update]) do |f| %>
  <% if @goal_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal_update.errors.count, "error") %> prohibited this goal_update from being saved:</h2>

      <ul>
      <% @goal_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_area :entry %>
    <%= f.hidden_field :goal_id, {:value => @goal.id} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goal_updates/edit.html.erb
<h1>Editing goal_update</h1>

<%= render 'form' %>

<%= link_to 'Show', [@goal, @goal_update] %> |
<%= link_to 'Back', goal_goal_updates_path %>

app/views/goal_updates/index.html.erb
<h1>Listing updates for <%= @goal.goal %></h1>

<%= month_calendar table: {class: "table table-bordered"}, tr: {class: "calendar-row"}, td: {class: "day"}, events: @goal_updates do |date, updates| %>
<%= date.strftime('%d') %>
  <% updates.each do |update| %>
  <p>
    <%= link_to update.updated_at.to_s(:time), [@goal, update] %>
    </p>
  <% end %>
<% end %>

<br>

<%= link_to 'New Goal Update', new_goal_goal_update_path(goal_id: @goal.id) %> | 
<%= link_to "Mark Complete", goal_mark_complete_path, method: :put %>

app/views/goal_updates/new.html.erb
<h1>New goal_update</h1>

<%= render 'form' %>

<%= link_to 'Back', goal_goal_updates_path %>

app/views/goal_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @goal_update.goal_id %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @goal_update.entry %>
</p>

<p>
  <strong>Update date:</strong>
  <%= @goal_update.update_date %>
</p>

<%= link_to 'Edit', [:edit, @goal, @goal_update] %> |
<%= link_to 'Back', goal_goal_updates_path %> |
<%= link_to 'Destroy', [@goal, @goal_update], method: :delete, data: { confirm: 'Are you sure?' } %>