config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :goals do
    put :mark_complete
    resources :goal_updates
  end

  get 'welcome/index'
  get 'welcome/index/:expand', to: 'welcome#index'
  get 'goals/index/:metagoal_id', to: 'goals#index'
  
  root 'welcome#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :user

	has_many :goal_updates

	has_many :goal_relationships, dependent: :delete_all
									
	has_many :subgoals, :class_name => "Goal",
						:foreign_key => "subgoal_id",
						through: :goal_relationships

	has_many :supergoals, :class_name => "Goal",
							:foreign_key => "goal_id",
							through: :goal_relationships

	validates :goal, presence: true

	
	
	

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  
  load_and_authorize_resource

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.where(:user_id => current_user.id)
    @title = "Your Goals"
    @expand_subgoal = params[:expand_subgoal]
    @complete = params[:complete]
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @title = "A Goal"
    render "show"
  end

  # GET /goals/new
  def new
    @goal = Goal.new(:user_id => params[:user_id].to_i)
    @title = 'New Goal'
    render "new"
  end

  # GET /goals/1/edit
  def edit
    @title = "Change your Goal"
    render "edit"
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_path }
      format.json { head :no_content }
    end
  end


  def mark_complete
    @goal = Goal.find(params[:goal_id])
    @goal.update_attributes(complete: true)
    redirect_to goals_path
  end


  private

  
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:goal, :description, :start, :end, :user_id, supergoal_ids: [], subgoal_ids: [])
    end


end

app/helpers/goals_helper.rb
module GoalsHelper



	def toggle_subgoals goal
	    if @expand_subgoal == goal.id.to_s
	      link_to 'Collapse Subgoals', goals_path(expand_subgoal: nil)  
	    else
	      link_to 'View Subgoals', goals_path(expand_subgoal: goal.id)
	      
	    end
	end

	 def find_subgoals goal
	 	GoalRelationship.where(subgoal_id: goal.id)
	 end

	def complete_toggle
		if @complete
			link_to "Show Active Goals", goals_path(complete: nil)
		else
			link_to "Show Completed Goals", goals_path(complete: true)
		end
	end

	def active_or_complete goal
		if @complete
			goal.where(complete: true)
		else
			goal.where(complete: nil)
		end
	end



end

app/views/goals/_form.html.erb
 <%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.hidden_field :user_id %>
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.date_select :end %>
  </div>
  <div class="field">
  <%= f.label :subgoal_of %><br>
  <%= f.collection_select(:subgoal_ids, Goal.where(:user_id => current_user.id).where(:complete => nil).where.not(:id => @goal.id), :id, :goal,  {include_blank: true}, {multiple: true}) %>
  </div>





  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Listing goals</h1>



<table class="table" >
<thead >
    <tr>
      <th class="text-center">Goal</th>
      <th class="text-center">Due Date</th>
      <th class="text-center">Updates</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% active_or_complete(@goals).each do |goal|  %>
      <tr>
        <% if goal.subgoals == [] %>
        <td><%= link_to goal.goal, goal %></td>
        <td><%= goal.end.to_s(:long_ordinal) %></td>
        <td><%= link_to "View updates", goal_goal_updates_path(goal.id) %> </td>
            <% find_subgoals(goal).each do |g| %>
            <% subgoal = Goal.find(g.goal_id) %>
            <%= render partial: 'layouts/table_row', locals: {subgoal: subgoal} %>
              
                <% end %>
              
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path(user_id: current_user.id) %> |
<%= complete_toggle %>

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @goal.goal %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @goal.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @goal.end %>
</p>


  <strong>Subgoal To:</strong>
  <% @goal.subgoals.each do |subgoal| %>
    <%= link_to "#{subgoal.goal}", subgoal %>
    <%end%>
  </p>

    <p>
  <strong>Subgoals:</strong>
  <% find_subgoals(@goal).each do |supergoal| %>
      <% g = Goal.find(supergoal.goal_id) %>
    <%= link_to "#{g.goal}", g %>
  <%end%>
  </p>
<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %> |
<%= link_to 'Delete', @goal, method: :delete, data: { confirm: 'Are you sure?' } %>