config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  resources :goals do
    put :mark_complete
    resources :goal_updates
  end

  get 'welcome/index'
  get 'welcome/index/:expand', to: 'welcome#index'
  get 'goals/index/:metagoal_id', to: 'goals#index'
  
  root 'welcome#index'

end

app/views/layouts/_header.html.erb
<p><%= link_to "Home", welcome_index_path %>

<%= link_to "View Goals", goals_path %>
<%= devise_links %>
</p>

app/views/layouts/_table_header.html.erb
<table>
  <thead>
    <tr>
      <th>Goal</th>
      <th>Due Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 </table>

app/views/layouts/_table_row.html.erb
    
      <tr>
        <td><%= link_to subgoal.goal, subgoal %></td>
        <td><%= subgoal.end.to_s(:long_ordinal) %></td>
        <td><%= link_to "View updates", goal_goal_updates_path(subgoal.id) %> </td>
        <% find_subgoals(subgoal).each do |g| %>
            <% subgoal = Goal.find(g.goal_id) %>
            <%= render partial: 'layouts/table_row', locals: {subgoal: subgoal} %>
            <% end %>
      </tr>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goalspec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
	body {
		font-family: arial, sans-serif;
		text-align: center;
		color: black;
		background-color: #EFEFEF;	
	}
	</style>
	<!-- Bootstrap -->
</head>
<body>

<%= render 'layouts/header' %>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 <script src="http://code.jquery.com/jquery.js"></script>

<%= yield %>

</body>
</html>